title: 'Faustine'
description: ''
about: ''
location: 'Durham'
email: faustineli12@gmail.com
baseurl: ""
url: 'faustineli.github.io'
twitter_username: your-name
github_username:  FaustineLi

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md