title: 'Faustine Li'
description: 'An aspiring MS student of Statistical Science at Duke University'
about: 'An aspiring MS student of Statistical Science at Duke University'
location: 'Durham, NC'
email: faustineli12@gmail.com
baseurl: ""
url: 
twitter_username: 
linkedin_username: FaustineLi
github_username:  FaustineLi

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
cv_btn: 'CV'
about_btn: 'About'
posts_btn: "Posts"
imprint_btn: "About"
contact_btn: 'Contact'
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md